### PR TITLE
fix: change to http default in github clone for dependencies

### PR DESCRIPTION
**Pull request by unparalleled-js**
### What I did

This works in CI better than SSH.

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]
Test locally to make sure it doesn't prompt for username and pasaword

**Comment by unparalleled-js** [comment]
It does not prompt me, but I don't remember if I configured it as such.  You can configure HTTPS to not prompt you. Maybe someone else can test as well? I am curious how CI will handle it.

**Comment by unparalleled-js** [comment]
you know - I believe it was using HTTPS before. When I removed pygit2, I accidentally switched the default... for what it's worth.

**Comment by fubuloubu** [comment]
> you know - I believe it was using HTTPS before. When I removed pygit2, I accidentally switched the default... for what it's worth.

That makes so much more sense lol

**Comment by fubuloubu** [comment]
Verified this works! okay to merge

**Review by NotPeopling2day — APPROVED** [review]

**Comment by fubuloubu** [comment]
I believe this still is not working for our CI action
https://github.com/fubuloubu/WETH8/actions/runs/3585793308/jobs/6034209359

**Pull request merged**
