### PR TITLE
feat: support python 3.13

### PR DESCRIPTION
**Pull request by bitwise-constructs**
### What I did

Adds in support for Python 3.13

fixes: 2392
Fixes: APE-1855

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by bitwise-constructs** [comment]
failing test should be fixed with https://github.com/jcrist/msgspec/pull/711

**Comment by antazoey** [comment]
Another random change to remember:

- [ ] Update black's language config in pyproject.toml file

**Comment by pcaversaccio** [comment]
> failing test should be fixed with [jcrist/msgspec#711](https://github.com/jcrist/msgspec/pull/711)

He hasn't released it yet and people are asking for it: https://github.com/jcrist/msgspec/issues/777. If it takes too long, would you guys be willing to do something like:

```txt
msgspec @ git+https://github.com/jcrist/msgspec@595c33c4a71c6d0c539b82233982a65819e240c
```

The reason why I ask is that I migrate snekmate to Python `3.13` here: https://github.com/pcaversaccio/snekmate/pull/291.

**Comment by bitwise-constructs** [comment]
@pcaversaccio instead I'm just going to remove the msgspec dep. will definitely get this out in next release

**Review by antazoey — APPROVED** [review]

**Pull request merged**
