### PR TITLE
fix: use getattribute [APE-1539]

### PR DESCRIPTION
**Pull request by antazoey**
### What I did

fixes: #1736 

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by mikeshultz — APPROVED** [review]
That sure is some confusing method naming there.  LGTM

**Comment by fubuloubu** [comment]
> That sure is some confusing method naming there. LGTM

https://stackoverflow.com/questions/3278077/difference-between-getattr-and-getattribute

**Comment by antazoey** [comment]
> That sure is some confusing method naming there. LGTM

You mean the dunders??

**Comment by mikeshultz** [comment]
> > That sure is some confusing method naming there. LGTM
> 
> You mean the dunders??

Yeah.  Having both `__getattr__` and `__getattribute__` with fairly different behaviors seems like a bad call.  Maybe it makes sense under the hood but from an API user perspective, it's confusing.

**Pull request merged**
