### PR TITLE
fix: avoid issues with pip by making it a core dependency

### PR DESCRIPTION
**Pull request by fubuloubu**
### What I did
Should hopefully take care of a few issues that arise from not having the latest version of `pip` when installing

### How I did it
Added `pip` to core dependencies

### How to verify it
Validate plugin installs

### Checklist

- [x] All changes are completed
- [x] ~~New test cases have been added~~
- [x] Documentation has been updated

### CODE REVIEW

**Review by NotPeopling2day — APPROVED** [review]

**Comment by fubuloubu** [comment]
Not working ugh
https://github.com/ApeWorX/ape-fantom/actions/runs/1973927487

**Review by unparalleled-js — APPROVED** [review]

**Comment by unparalleled-js** [comment]
I think this solution does not meet our needs.

Reason: We need to ensure pip is up-to-date _before_ running the `setup.py`. Otherwise, I think the install process uses the `pip` that was installed from the start and does not update in time.

**Review by unparalleled-js — CHANGES_REQUESTED** [review]
I think we should probably close this; I don't think it will work :/
It was a nice idea though!

**Comment by fubuloubu** [comment]
You're right, I don't think this would work correctly.

**Pull request closed without merging**
