### PR TITLE
feat: allow iteration/existance checking contract types in project

### PR DESCRIPTION
**Pull request by fubuloubu**
### What I did
quick little PR to allow checking if a contract name is in a project e.g. `"MyContract" in project`

### CODE REVIEW

**Review by unparalleled-js — APPROVED** [review]
LGTM

I tested it out and will use this in my demo project.

**Comment by unparalleled-js** [comment]
Hmm... Actually, when I do 

```
    account = get_account()
    for contract in project:
        return account.deploy(project[contract], *args, **kwargs)
```

I get error `TypeError: 'ProjectManager' object is not subscriptable`

**Comment by unparalleled-js** [comment]
I _am_ able to check if it `"Fund" in project` though

**Comment by unparalleled-js** [comment]
Maybe we should also either make the ProjectManager subscriptable or make a `get_contract()` method so we can loop through the contract and deploy them all. Otherwise, I have to use `getattr()` to access each contract type

**Comment by fubuloubu** [comment]
> I _am_ able to check if it `"Fund" in project` though
> 
> Edit: Realize I am also able to iterate but wondering about the UX of accessing the contracts while looping

beginning to think that since we already have `project.contracts`, we should just use that instead e.g. `if "MyContract" in project.contracts: return project.MyContract`

**Comment by unparalleled-js** [comment]
> > I _am_ able to check if it `"Fund" in project` though
> > Edit: Realize I am also able to iterate but wondering about the UX of accessing the contracts while looping
> 
> beginning to think that since we already have `project.contracts`, we should just use that instead e.g. `if "MyContract" in project.contracts: return project.MyContract`

Explicit is good.. Looping through a project might be confusing, like I am looping through the project's test and scripts or contracts, it might not be clear as day

**Comment by fubuloubu** [comment]
closing as not needed

use `project.contracts` instead

**Pull request closed without merging**
