### PR TITLE
docs: add anonymized analytics

### PR DESCRIPTION
**Pull request by fubuloubu**
### What I did

It would be really helpful for us to monitor growth by seeing our analytics from the docs page

fixes: APE-453

### How I did it

I chose Plausible because they are privacy-preserving and open source

### How to verify it

Once docs are released (on main) should be able to see the page

### CODE REVIEW

**Comment by fubuloubu** [comment]
Also found this: https://www.goatcounter.com/

**Comment by fubuloubu** [comment]
Another: https://github.com/plausible/analytics

**Comment by unparalleled-js** [comment]
Note, I had to switch to Chrome (and not Brave) to get the script to not be blocked.

**Review by unparalleled-js — DISMISSED** [review]
I did get the script to load on chrome. Does anything show up on the account?

**Comment by fubuloubu** [comment]
Hmm, do all scripts get blocked by brave by default?

**Comment by unparalleled-js** [comment]
There is also the chance the privacy-browser purposely misleads the analytics tools, in the case to avoid penalty.

https://brave.com/privacy-updates/1-web-resource-replacements/#solution-dont-just-block-replace

**Comment by fubuloubu** [comment]
I wish github pages just had analytics so it could tell us how many downloads we were getting lol

**Comment by unparalleled-js** [comment]
Maybe we should try the other 2 that you linked and see if they are considered "trackers" by Brave?

The GOAT one seems like it may be cognizant of this.

**Comment by fubuloubu** [comment]
> Maybe we should try the other 2 that you linked and see if they are considered "trackers" by Brave?
> 
> The GOAT one seems like it may be cognizant of this.
> 

I'm into this. I like that the others are open source

**Comment by fubuloubu** [comment]
> I did get the script to load on chrome. Does anything show up on the account?

Try again, it wasn't watching

**Comment by fubuloubu** [comment]
> It works on Chrome but not Brave! I don't expect it to work on Brave though.

There's a way to set it up with a proxy method which may bypass this, but not screwing around with this now

> I like how easy it integrates with our docs stack too.

Yeah, it's a 3rd party plugin, but seems relatively active so that's cool.

**Pull request merged**
