### PR TITLE
feat!: Make OutOfGasError a VirtualMachineError

### PR DESCRIPTION
**Pull request by Ninjagod1251**
### What I did

fixes: [Ape-369](https://linear.app/apeworx/issue/APE-369/make-outofgaserror-a-virtualmachineerror) 

fixes: APE-369
change the base class of outofgas to virtualmachineError

### Checklist

- [x] All changes are completed
- [x] New test cases have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by vany365** [comment]
APE-369

**Review by sabotagebeats — DISMISSED** [review]
does this need tests?

**Comment by fubuloubu** [comment]
> does this need tests?

don't think it needs anything additional, more a UX thing

**Comment by unparalleled-js** [comment]
> does this need tests?

It is tested by the fact that we should now be able to remove this type ignore: https://github.com/ApeWorX/ape-hardhat/blob/main/ape_hardhat/provider.py#L483

**Review by sabotagebeats — APPROVED** [review]
LGTM

**Pull request merged**
