### PR TITLE
feat: add notebook server support

### PR DESCRIPTION
**Pull request by fubuloubu**
### What I did
Add rudimentary notebook support using Jupyter's notebook

fixes: #63

### Checklist

- [ ] Integrate the command more deeply with our Click cli infrastructure
- [ ] Add the console extras and ape top-level types into the notebook's namespace
- [ ] Add network option to notebook
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by johnson2427** [comment]
@fubuloubu you said you stood up a server for this, should I pull this branch to work on this, or did you want to have a quick meet to go over this jupyter issue?

**Comment by johnson2427** [comment]
Moving this to a 2nd class plugin instead

**Comment by johnson2427** [comment]
Can I close this PR?

**Comment by fubuloubu** [comment]
> Can I close this PR?

yes

**Pull request closed without merging**
