### PR TITLE
feat!: update cached compilers improvements [APE-1500]

### PR DESCRIPTION
**Pull request by antazoey**
### What I did

* Allows easily updating the project manifest cache.
* Allows CompilerAPI to add the compiler ethpm classes and acknowledges those (more secure and accurate to use the settings _actually_ used when doing verification)

### How I did it

* Create method for updating it and share some stuff
* Refactor: general breaking change improvements that shouldnt really matter
* feat: honor compilers output

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by antazoey** [comment]
this isnt working yet... lots of problems... but i know what to do.

**Comment by antazoey** [comment]
ok i may actually need this now... trying to fix etherscan verification

**Comment by antazoey** [comment]
required https://github.com/ApeWorX/ethpm-types/pull/103

**Review by fubuloubu — APPROVED** [review]

**Comment by antazoey** [comment]
now, i have compilers being output in `ape-solidity` and about to make sure is being used in ape-etherscan.
maybe it won't fix our verification bug, maybe it will... but in any case, the settings are 100% more honest now and i think that is a huge win.

still need to do same in ape-vyper pr

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
