### PR TITLE
feat!: upgrade dockerfile to python 3.10 [APE-1112]

### PR DESCRIPTION
**Pull request by sabotagebeats**
### What I did

upgrade dockerfile to python 3.10 by using python 3.10 slim base image

### How I did it

wanted to have python 3.10 as base image so that using python 3.10 

### How to verify it

`docker build -t ape .`
`docker run -it --entrypoint /bin/bash ape`
```
harambe@09814ecfcd49:~/project$ python --version
Python 3.10.12
```

### Checklist

- [x] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by antazoey** [comment]
Is this a breaking change for the image? Wondering if this should happen in 0.7 versus now.

Note, you can set PYTHON_ARG="3.10" in silverback if you need to

**Comment by sabotagebeats** [comment]
this can wait for a later version if this is a breaking change, but it doesn't seem to break anything for me? 

> Is this a breaking change for the image? Wondering if this should happen in 0.7 versus now.
> 
> Note, you can set PYTHON_ARG="3.10" in silverback if you need to

**Comment by fubuloubu** [comment]
> Is this a breaking change for the image? Wondering if this should happen in 0.7 versus now.
> 
> Note, you can set PYTHON_ARG="3.10" in silverback if you need to

I agree with @antazoey, this could be a breaking change, and there's a workaround for now

**Comment by sabotagebeats** [comment]
@antazoey should I close this or leave it open?

**Comment by fubuloubu** [comment]
I think we should migrate everything that only used 3.8 to 3.10 when we migrate things for the v0.7.0 release (such as linting CI, base image, etc.)

**Comment by sabotagebeats** [comment]
I think this is now a blocker for chaosnet ApePay integration.

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
