### PR TITLE
fix: remove italics from last PR [APE-1168]

### PR DESCRIPTION
**Pull request by antazoey**
### What I did

fixes: #

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by banteg** [comment]
reason: italics would render as inverse text (black text on white background) in the default `tmux` config. it requires `TERM` to be set to `xterm-256color` to render properly. `screen-256color` doesn't support italics.

**Comment by antazoey** [comment]
@banteg also suggested to include ipt names as well; we are doing that now, but leverage ethpm-types

**Comment by antazoey** [comment]
mypy is failing from latest click upgrade

**Comment by antazoey** [comment]
it is easier to just pin click then try to resolve all the "issues" https://github.com/pallets/click/issues/2558

**Pull request merged**
