### PR TITLE
refactor!: Upgrade Ethereum packages and usage

### PR DESCRIPTION
**Pull request by antazoey**
### What I did

in prep for the eth upgrades, we need to do this

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by fubuloubu — DISMISSED** [review]

**Comment by antazoey** [comment]
shares most with https://github.com/ApeWorX/ape/pull/2223 but this one is the breaking changes version.
the diff will be much simpler after 2223.
unfortunately we cant update web3.py officially until we are ready for 0.9 as it breaks plugins

**Review by bitwise-constructs — APPROVED** [review]

**Review by fubuloubu — COMMENTED** [review]
seems like some changes are mixed together in here?

**Comment by antazoey** [comment]
> seems like some changes are mixed together in here?

The base path is out of date.

**Review by fubuloubu — APPROVED** [review]

**Comment by bitwise-constructs** [comment]
upgrading to web3.py>7 will allow https://github.com/ApeWorX/ape-polygon/issues/33 to be fixed

**Comment by antazoey** [comment]
> upgrading to web3.py>7 will allow [ApeWorX/ape-polygon#33](https://github.com/ApeWorX/ape-polygon/issues/33) to be fixed

itll be a while until 0.9 is out.

**Pull request merged**
