### PR TITLE
chore: add windows to CI matrix

### PR DESCRIPTION
**Pull request by fubuloubu**
### What I did

Related issue: #95

### CODE REVIEW

**Comment by fubuloubu** [comment]
blocked on #91

**Comment by unparalleled-js** [comment]
@fubuloubu This PR was opened in July and seems to only change a single line of code.
Can we close this and re-pick it up when we are able?

**Comment by fubuloubu** [comment]
> @fubuloubu This PR was opened in July and seems to only change a single line of code. Can we close this and re-pick it up when we are able?

I think we can just keep it around as a reminder to keep trying this every once in a while

Single line means very unlikely to have a merge conflict!

**Comment by johnson2427** [comment]
I have no idea how I broke github so badly on this one, but wow

**Comment by johnson2427** [comment]
pyethash hasn't been updated since 2015, and it's the crux of this issue in windows

**Comment by fubuloubu** [comment]
No worries, this is a known issue blocking this

Something new is that @banteg wanted to explore using pysha3 backend instead, which might work for windows

**Comment by NotPeopling2day** [comment]
I attempted to rebase this ticket, but the scope continues to grow and additional work will be needed to integrate the geth installation process. I'm closing the ticket in favor of a backlog issue we can track on this work.

https://linear.app/apeworx/issue/APE-116/general-windows-support

**Pull request closed without merging**
