### PR TITLE
feat!: add automine abstract property to TestProviderAPI

### PR DESCRIPTION
**Pull request by antazoey**
fixes: #1968

can't merge because this is a breaking change.

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]
Can't it just raise NotImplementedError for now until 0.8?

**Comment by antazoey** [comment]
> Can't it just raise NotImplementedError for now until 0.8?

It could I guess. Might as well wait though. Functionality wise, you can use this feature on the providers that support it (ape-test and ape-foundry) so no one should be blocked.

**Review by fubuloubu — APPROVED** [review]
Approved for v0.8

Question: does `ape-test` provider not support?

**Comment by antazoey** [comment]
> Question: does `ape-test` provider not support?

It does, it was added here: https://github.com/ApeWorX/ape/pull/1972

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
