### PR TITLE
chore: allow rich v13 as dependency

### PR DESCRIPTION
**Pull request by mikeshultz**
### What I did

Expanded the allowed dependency version of the rich package to include v13.

### How to verify it

Output looks the same on tree list commands and tests pass.

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by antazoey — APPROVED** [review]

**Review by fubuloubu — APPROVED** [review]
Do we want to lower pin against v13?

**Comment by mikeshultz** [comment]
> Do we want to lower pin against v13?

I'm not sure what you mean by this.

**Comment by fubuloubu** [comment]
> > Do we want to lower pin against v13?
> 
> I'm not sure what you mean by this.

Upgrade the pin from 12.5.1 to whatever latest 13 is

**Comment by mikeshultz** [comment]
> > > Do we want to lower pin against v13?
> > 
> > 
> > I'm not sure what you mean by this.
> 
> Upgrade the pin from 12.5.1 to whatever latest 13 is

After wrestling with dependencies with overly restrictive dependency specs over the last week I'm not especially wanting to do the same to others just because I'm toying around with something.  Also, our API exposure to rich is super limited on this one so I think we're pretty safe here for the time being.

**Pull request merged**
