### PR TITLE
docs: quickstart update

### PR DESCRIPTION
**Pull request by Ninjagod1251**
### What I did

Updated quickstart guide:
Removed all the comments related to issues and questions about certain commands

fixes: #

Fixed the  issue of PR request in sabotage fork by creating a PR from my own branch docs/chris which is off the main branch

### How I did it

Provided solutions to the questions I replaced. I also provided examples
I also used livesphinix.herokuapp.com to preview the changes

### How to verify it

Preview the changes to verifiy in the PR preview on GitHub

### Checklist

- [ ] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [ ] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Comment by sabotagebeats** [comment]
@Ninjagod1251 we will fix up this pull tomorrow together

**Comment by sabotagebeats** [comment]
also if younotice the checks are passing here

**Comment by unparalleled-js** [comment]
This PR has all the changes from Sabo's branch, you probably want these changes on a separate branch and Pull Request

**Comment by sabotagebeats** [comment]
> This PR has all the changes from Sabo's branch, you probably want these changes on a separate branch and Pull Request

@unparalleled-js These changes will conflict with the current `quickstart` in 193 https://github.com/ApeWorX/ape/pull/193 which is ready to merge. After I can pair with @Ninjagod1251 to pull from main and implement these `quickstart` changes on top of that. After that then we can request review of this pull.

**Review by sabotagebeats — APPROVED** [review]
Looks good to me

**Review by fubuloubu — APPROVED** [review]

**Pull request merged**
