### PR TITLE
fix: scripts not running unless click script in scripts folder [APE-634]

### PR DESCRIPTION
**Pull request by sabotagebeats**
### What I did

changed the suffix to be able to detect `.` from subdirectories to fix bug where subdirectory scripts would not run unless there was a click script in the `/scripts/` folder. 

fixes: #1302
fixes: APE-630

### How I did it

detects `.` in the suffix in order to see if it is in the main scripts folder or is in a subdirectory, then returns the suffix accordingly

### How to verify it

tests run, can also try in a project with scripts only in subdirectories (this is working for me)

### Checklist

- [x] All changes are completed
- [x] New test cases have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by fubuloubu** [comment]
@sabotagebeats test would be good to see for this

**Comment by sabotagebeats** [comment]
@fubuloubu sounds good! working on that.

**Comment by sabotagebeats** [comment]
test added

**Comment by sabotagebeats** [comment]
tests passing, ready for review.

**Review by unparalleled-js — APPROVED** [review]
Good catch!

**Pull request merged**
