### PR TITLE
feat: reduced docker build size to 448MB from 1.7GB [APE-702]

### PR DESCRIPTION
**Pull request by sabotagebeats**
### What I did

1. remove apt-get commands as they were no longer needed and a security issue
2. use a docker python build image to build the wheel files
3. copy the wheel files to a new docker image using -slim
4. install the wheel files

fixes: #

### How I did it

reducing docker build size because it is big and annoying

### How to verify it

`docker build . && docker images`

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by sabotagebeats** [comment]
was able to get it to 446MB but I could get it to 441MB without installing the recommended-plugins but I don't know if that small of a reduction is worth it.

**Review by fubuloubu — APPROVED** [review]
Great reduction! Needs some validation that everything still works as intended

**Comment by sabotagebeats** [comment]
> Great reduction! Needs some validation that everything still works as intended

@fubuloubu i was doing some local testing and it works the same as the other image for generating accounts, connecting to mainnet, checking chain networks, compiling contracts. Is there a way we can feed this into the GitHub actions for more automated testing? I think right now we are just testing in GitHub actions with the && ape version.

**Comment by fubuloubu** [comment]
> Is there a way we can feed this into the GitHub actions for more automated testing? I think right now we are just testing in GitHub actions with the && ape version. 

I don't necessarily know of a way to do this, but would be open to that. If the container starts and runs effectively I think that's a decent test, but for supporting more unique use cases of the container probably would be better to test it for those use cases

**Comment by sabotagebeats** [comment]
>
> for supporting more unique use cases of the container probably would be better to test it for those use cases
> 
> 
I can test it out some more and let you know

**Comment by sabotagebeats** [comment]
@fubuloubu this is working with my fastapi test project as well.

**Comment by fubuloubu** [comment]
> @fubuloubu this is working with my fastapi test project as well.

Sick, let's give it a day to see if one of the Yearn folks gets a chance to test it and then we can merge

**Comment by sabotagebeats** [comment]
merging as per tg discussion

**Comment by PoCk3T-SPAI** [comment]
That broke compatibility with the apex/ape-avalanche plugin @sabotagebeats 
Building my own Docker image based on apeworx/ape:latest Dockerhub image now throws that error at this part of my Dockerfile:
`RUN ape plugins install polygon ethereum bsc avalanche arbitrum optimism fantom starknet solidity alchemy infura etherscan --upgrade`:

```
starting build "a7300fbc-b0a8-421f-b1f7-4db0647622d3"

FETCHSOURCE
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/polkadot-validation-360201/r/bitbucket_spiderwebdotai_mvp-web3-devops-oracle
 * branch            48c3b639ba8b59b9a35228a77fb6447c2edfeade -> FETCH_HEAD
HEAD is now at 48c3b63 Redirecting ERC1155 metadata to a dedicated JPG logo - served by this micro-service directly (committing image too)
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker
Sending build context to Docker daemon  40.27MB

Step 1/8 : FROM apeworx/ape:latest
latest: Pulling from apeworx/ape
3f9582a2cbe7: Already exists
57d9937f91c0: Pulling fs layer
0cb86c94bd49: Pulling fs layer
86597112c628: Pulling fs layer
4eecfebe9e2b: Pulling fs layer
e458acf34aa8: Pulling fs layer
6078f8ad4ecf: Pulling fs layer
1e4124718660: Pulling fs layer
e10501a5f258: Pulling fs layer
415d1774cbb1: Pulling fs layer
4eecfebe9e2b: Waiting
e458acf34aa8: Waiting
6078f8ad4ecf: Waiting
1e4124718660: Waiting
e10501a5f258: Waiting
415d1774cbb1: Waiting
86597112c628: Verifying Checksum
86597112c628: Download complete
57d9937f91c0: Verifying Checksum
57d9937f91c0: Download complete
0cb86c94bd49: Verifying Checksum
0cb86c94bd49: Download complete
57d9937f91c0: Pull complete
4eecfebe9e2b: Verifying Checksum
4eecfebe9e2b: Download complete
1e4124718660: Verifying Checksum
1e4124718660: Download complete
e458acf34aa8: Verifying Checksum
e458acf34aa8: Download complete
415d1774cbb1: Verifying Checksum
415d1774cbb1: Download complete
0cb86c94bd49: Pull complete
86597112c628: Pull complete
6078f8ad4ecf: Verifying Checksum
6078f8ad4ecf: Download complete
4eecfebe9e2b: Pull complete
e10501a5f258: Verifying Checksum
e10501a5f258: Download complete
e458acf34aa8: Pull complete
6078f8ad4ecf: Pull complete
1e4124718660: Pull complete
e10501a5f258: Pull complete
415d1774cbb1: Pull complete
Digest: sha256:b508d552d95644dcd2e58ef94486e9a7d6860acdfdaf95ff42b42b46e5b67e6d
Status: Downloaded newer image for apeworx/ape:latest
 ---> ba37c8d71838
Step 2/8 : WORKDIR /home/harambe/project
 ---> Running in 07dafe3a0117
Removing intermediate container 07dafe3a0117
 ---> 02804b1bf007
Step 3/8 : RUN ape plugins install polygon ethereum bsc avalanche arbitrum optimism fantom starknet solidity alchemy infura etherscan --upgrade
 ---> Running in d69a494b532f
INFO: Upgrading 'polygon'...
SUCCESS: Plugin 'polygon' has been upgraded to version 0.6.0.
ERROR: Cannot install core 'ape' plugin 'ethereum'.
INFO: Upgrading 'bsc'...
SUCCESS: Plugin 'bsc' has been upgraded to version 0.6.0.
INFO: Upgrading 'avalanche'...
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/__init__.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/util.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/test_util.py -> build/lib.linux-x86_64-3.9/bitarray
      running build_ext
      building 'bitarray._bitarray' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/bitarray
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.9/bitarray/_bitarray.o
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bitarray

  error: subprocess-exited-with-error
  
  × Running setup.py install for bitarray did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/__init__.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/util.py -> build/lib.linux-x86_64-3.9/bitarray
      copying bitarray/test_util.py -> build/lib.linux-x86_64-3.9/bitarray
      running build_ext
      building 'bitarray._bitarray' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/bitarray
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.9 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.9/bitarray/_bitarray.o
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> bitarray
```

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI please try this, it is working for me: 


Dockerfile:
```
FROM apeworx/ape:latest

RUN apt-get update \
    && apt-get install -y \
    --no-install-recommends -o \
    APT::Immediate-Configure=false \
    gcc g++
    
RUN ape plugins install \
    polygon \
    ethereum \
    bsc \
    avalanche \
    arbitrum \
    optimism \
    fantom \
    starknet \
    solidity \
    alchemy \
    infura \
    etherscan \
    --upgrade
```
this will increase image size from 446MB to 841MB

if you want to make it smaller you can use us as a build image (like I did in our dockerfile), then install gcc, then install the plugins, then build wheels, then copy wheels to our base image (like I did in our dockerfile)

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI I've created this issue to track this bug so it doesn't get lost in the sauce. 
https://github.com/ApeWorX/ape/issues/1336

**Comment by PoCk3T-SPAI** [comment]
Oh nice, thanks again @sabotagebeats , love the developer activity on this project

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI thanks for the compliment! I appreciate you!

**Pull request merged**
