### PR TITLE
chore: upgrade pytest

### PR DESCRIPTION
**Pull request by unparalleled-js**
### What I did

Bump pytest because I keep installing Ape in an environment where pytest is in the 7 range.

### How I did it

bumps!

### How to verify it

Your tests to run / work as expected for your ape projects!!!
Remember: pytest is a core dependency.

### Checklist

- [ ] All changes are completed
- [ ] New test cases have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by NotPeopling2day — DISMISSED** [review]
LGTM

**Review by fubuloubu — APPROVED** [review]

**Comment by fubuloubu** [comment]
although probably need to update every plugin too

**Comment by unparalleled-js** [comment]
> although probably need to update every plugin too

It only affects dev-installs of plugins, so it is not critical / breaking. But yeah, it would need to happen

**Comment by unparalleled-js** [comment]
Let's save this for the next big release anyway and then adjust pytest dev dependency at the same time!

**Comment by unparalleled-js** [comment]
I am pretty sure we can support both 6 and 7, which makes this not a breaking change

**Review by fubuloubu — APPROVED** [review]
As long as the wide pin causes no breaking changes, that's fine, I do worry about features we might use which exist in one major and not the other

**Pull request merged**
